name: Docker - Tasks Service

on:
  push:
    tags: ["v*"]
    paths:
      - 'mofumofu-backend/tasks/**'
      - '.github/workflows/docker-tasks.yml'
  pull_request:
    branches: ["main"]
    paths:
      - 'mofumofu-backend/tasks/**'
      - '.github/workflows/docker-tasks.yml'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-tasks

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./mofumofu-backend/tasks
          file: ./mofumofu-backend/tasks/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64

      - name: Test Docker image
        if: github.event_name == 'pull_request'
        run: |
          echo "Testing Tasks service Docker image..."
          docker images ${{ env.IMAGE_NAME }}:test || docker images | grep tasks
          echo "✅ Tasks service Docker image built successfully"